name: HTMLCheck
on:
  push:
    branches:
      - main

jobs:
  TestHtml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Prettier
        run: npm install -g prettier

      - name: Check HTML Syntax
        run: prettier --check "*.html"

      
